<a href="https://colab.research.google.com/github/makl1/MLTraining/blob/master/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
weights = [ [0.1, 0.1, -0.3],# hurt?
[0.1, 0.2, 0.0], # win?
[0.0, 1.3, 0.1] ]# sad?

def w_sum(a,b):
  assert(len(a)== len(b))
  output = 0
  for i in range(len(a)):
    output += (a[i]*b[i])
  return output

def vect_mat_mul(vect,matrix):
  assert(len(vect) == len(matrix))
  output =[0,0,0]
  for i in range(len(vect)):
    print("MAtrix-"+ str(matrix[i]))
    output[i] = w_sum(vect,matrix[i])
  return output

def neural_network(input, weights):
  pred = vect_mat_mul(input,weights)
  return pred

def vect_out_multiply(vec_a,vec_b):  
  out = np.zeros((len(vec_a),len(vec_b)))
  for i in range(len(vec_a)):
    for j in range(len(vec_b)):
      out[i][j] = vec_a[i]*vec_b[j]
  return out

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
hurt = [0.1, 0.0, 0.0, 0.1]
win = [ 1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]
alpha = 0.01
input = [toes[0],wlrec[0],nfans[0]]
true = [hurt[0], win[0], sad[0]]
pred = neural_network(input,weights)
error = [0,0,0]
delta =[0,0,0]
for i in range(len(true)):
  error[i] = (pred[i] - true[i])**2
  delta[i] = pred[i] - true[i]
weight_deltas = vect_out_multiply(delta,input)

for i in range(len(weights)):
  for j in range(len(weights[i])):
    weights[i][j] -= alpha * weight_deltas[i][j]


print(weights)

MAtrix-[0.1, 0.1, -0.3]
MAtrix-[0.1, 0.2, 0.0]
MAtrix-[0.0, 1.3, 0.1]
[[0.061325, 0.0970425, -0.30546], [0.1017, 0.20013, 0.00023999999999999887], [-0.07352500000000001, 1.2943775, 0.08962]]


In [ ]:
import numpy as np
weights = np.array([0.5,0.0,-0.5])
alpha = 0.1
streetlights = np.array( [[ 1, 0, 1 ],
[ 0, 1, 1 ],
[ 0, 0, 1 ],
[ 1, 1, 1 ],
[ 0, 1, 1 ],
[ 1, 0, 1 ] ] )
walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )
for iteration in range(40):
  error_all =0
  for i in range(len(walk_vs_stop)):
    input = streetlights[i]    
    goal_pred = walk_vs_stop[i]
    pred = input.dot(weights)
    error = (pred-goal_pred)**2
    error_all += error
    delta = pred- goal_pred
    weight_delta = input * delta
    weights -= alpha * weight_delta
    print("Prediction-"+str(pred))
    print ("error" + str(error_all))
print ("Weights -" + str(weights))

Prediction-0.0
error0.0
Prediction--0.5
error2.25
Prediction--0.35
error2.3725
Prediction-0.335
error2.814725
Prediction--0.03199999999999997
error3.8797490000000003
Prediction-0.4212
error4.05715844
Prediction-0.33696
error0.11354204159999999
Prediction-0.09858400000000006
error0.926092846656
Prediction--0.1309744
error0.94324714011136
Prediction-0.7826486399999999
error0.9904887538052096
Prediction-0.33543491200000003
error1.4321355099936575
Prediction-0.48273382080000005
error1.665167451737824
Prediction-0.38618705664
error0.14914044271626659
Prediction-0.381455841856
error0.5317373182903362
Prediction--0.054722987129599984
error0.5347319236107225
Prediction-0.93616402045376
error0.5388069558953505
Prediction-0.523404168107008
error0.7659505428731237
Prediction-0.43670313893790724
error0.9566601744313448
Prediction-0.3493625111503258
error0.12205416419726152
Prediction-0.540116769476783
error0.33354674991373184
Prediction--0.02782574922921839
error0.3343210222338992
Prediction-0.988

In [ ]:
import numpy as np
np.random.seed(1)

def relu(x):
  return (x>0)*x

def relu_deriv(x):
  return (x>0)

alpha = 0.2
hidden_size = 4
streetlights = np.array( [[ 1, 0, 1 ],
[ 0, 1, 1 ],
[ 0, 0, 1 ],
[ 1, 1, 1 ] ] )
print("StreetLights- " + str(streetlights[0]))
walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

weights_1 = 2*np.random.random((3, hidden_size))-1
print(weights_1)
weights_2 = 2*np.random.random((hidden_size,1))-1
print(weights_2)
layer_2_error = 0

for iteration in range(60):
  layer_2_error = 0
  for i in range(len(streetlights)):
    layer_0 = streetlights[i:i+1] 
    print(layer_0)
    layer_1 = relu(np.dot(layer_0,weights_1)) 
    print("layer_1 - "+ str(layer_1))
    layer_2 = np.dot(layer_1,weights_2)
    print("layer_2 - "+ str(layer_2))
    layer_2_error += np.sum((layer_2-walk_vs_stop[i:i+1])) **2
    layer_2_delta = layer_2-walk_vs_stop[i:i+1]
    layer_1_delta = layer_2_delta.dot(weights_2.T)* relu_deriv(layer_1)
    weights_1 -= alpha * layer_0.T.dot(layer_1_delta)
    weights_2 -=alpha * layer_1.T.dot(layer_2_delta)
  if(iteration % 10 == 9):
    print("Error:" + str(layer_2_error))

StreetLights- [1 0 1]
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
[[1 0 1]]
layer_1 - [[-0.          0.51828245 -0.         -0.        ]]
layer_2 - [[0.39194327]]
[[0 1 1]]
layer_1 - [[-0.         -0.         -0.          0.06156045]]
layer_2 - [[0.02098811]]
[[0 0 1]]
layer_1 - [[-0.          0.16960021 -0.          0.43719489]]
layer_2 - [[0.29327219]]
[[1 1 1]]
layer_1 - [[-0. -0. -0. -0.]]
layer_2 - [[0.]]
[[1 0 1]]
layer_1 - [[-0.          0.65416247 -0.          0.02115568]]
layer_2 - [[0.53634943]]
[[0 1 1]]
layer_1 - [[-0.         -0.         -0.          0.20472264]]
layer_2 - [[0.06741661]]
[[0 0 1]]
layer_1 - [[-0.          0.19659472 -0.          0.50826656]]
layer_2 - [[0.35781632]]
[[1 1 1]]
layer_1 - [[-0. -0. -0. -0.]]
layer_2 - [[0.]]
[[1 0 1]]
layer_1 - [[-0.          0.74200005 -0.          0.116987

In [ ]:
import numpy as np
vector=np.array([1,2,1])
matrix = np.array([[5,1,3,4],
                  [1,1,1,1],
                  [1,2,1,0]])
print(vector.dot(matrix))

[8 5 6 6]


In [ ]:
import numpy as np
from keras.datasets import mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
images,labels = (x_train[0:1000].reshape(1000,28*28) /255, y_train[0:1000])
print("Images:"+str(images))
print(labels)

Images:[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 6 9 0 5 6
 0 7 6 1 8 7 9 3 9 8 5 9 3 3 0 7 4 9 8 0 9 4 1 4 4 6 0 4 5 6 1 0 0 1 7 1 6
 3 0 2 1 1 7 9 0 2 6 7 8 3 9 0 4 6 7 4 6 8 0 7 8 3 1 5 7 1 7 1 1 6 3 0 2 9
 3 1 1 0 4 9 2 0 0 2 0 2 7 1 8 6 4 1 6 3 4 5 9 1 3 3 8 5 4 7 7 4 2 8 5 8 6
 7 3 4 6 1 9 9 6 0 3 7 2 8 2 9 4 4 6 4 9 7 0 9 2 9 5 1 5 9 1 2 3 2 3 5 9 1
 7 6 2 8 2 2 5 0 7 4 9 7 8 3 2 1 1 8 3 6 1 0 3 1 0 0 1 7 2 7 3 0 4 6 5 2 6
 4 7 1 8 9 9 3 0 7 1 0 2 0 3 5 4 6 5 8 6 3 7 5 8 0 9 1 0 3 1 2 2 3 3 6 4 7
 5 0 6 2 7 9 8 5 9 2 1 1 4 4 5 6 4 1 2 5 3 9 3 9 0 5 9 6 5 7 4 1 3 4 0 4 8
 0 4 3 6 8 7 6 0 9 7 5 7 2 1 1 6 8 9 4 1 5 2 2 9 0 3 9 6 7 2 0 3 5 4 3 6 5
 8 9 5 4 7 4 2 7 3 4 8 9 1 9 2 8 7 9 1 8 7 4 1 3 1 1 0 2 3 9 4 9 2 1 6 8 4
 7 7 4 4 9 2 5 7 2 4 4 2 1 9 7 2 8 7 6 9 2 2 3 8 1 6 5 1 1 0 2 6 4 5 8 3 1
 5 1 9 2 7 4